language: node_js
cache: yarn
node_js:
- node
dist: trusty
sudo: false
before_install: yarn global add greenkeeper-lockfile@1
install:
- yarn
before_script: greenkeeper-lockfile-update
script:
- yarn build
after_script: greenkeeper-lockfile-upload
notifications:
  slack:
    secure: Yvry7xfORKc/qK4QVxYf6EzAGc37p7xhKa8xHk/DwDLjvJinhQy84nKBrTuqU148efjVf6e0qzulrutjx81F/Ewh1seAhKNNntobUgz+VSsJXvsalQtdyAP8iQRQiQXBWnvtPzpgv5uXbRcj35UadfDS7g9YMJj8AYoOwADLCZudNcat4E2PoFvV/oHrA9inI/lqY2ZFZEIpkh2ouUFMPlVcATL6uTmNOnxh9/QoHKhxb2BSS/rNabiE3MnvTYCtj9t82o8/Rl7pOkQ5kjPkhFANB7EM3uFXoflkTHMaNsM+MaGTcDJBx03bPMc1pfBz8UbTj0PJNdEuIvRqToFoLw1yKb5nJAylVFZbm2a6+Pxk4j0ddAnTXja1CPFlr3bFOjx7FggXpN23QqVZhotPTjz68sk+kSU7NhDvn2OStdWimNG0H/utFGZQMFMt8wkKrFEMlNVI412cFYgCBZhVMg9xsKBg4zxcjehx8a39VgLUwioiOg/Wxq5Ckdfj3xbh5aIq6JIo/ltMqqOBcGZSSHEAabDSlXzL3tnqAneMVK5I+yQropaqFRHwzO8DKnMMasApnaI2NfubrN5TlTztgTeEqKXPdr84AqkYTiVqfILT3NqEFB9ErAuc06vZbqtXGjj/Cq8Y0G7GhKfM0afAK+B5tH53nb4I9Kk87tZ1fGc=
